authors:
  MissPenguin:
    name: MissPenguin
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/25809855?v=4
    url: https://github.com/MissPenguin
  Evezerest:
    name: Evezerest
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/50011306?v=4
    url: https://github.com/Evezerest